# Reference: https://wiki.hypr.land/Configuring/

# Variables
# $SCRIPT_DIR = ~/.dotfiles/linux/scripts
$SCRIPT_DIR = ~/.dotfiles/lainbook_linux/scripts

# Theme
source = themes/catppuccin_mocha.conf

# Load profile
; source = hyprland/profile.conf

# Initialize Hyprland
source = hyprland/init.conf

# Load other Config
source = hyprland/profile.conf

source = hyprland/plugins.conf

source = hyprland/binds.conf

general {
    layout = scrolling
}

#######################
##### Peripherals #####
#######################
# Monitor
# Reference: https://wiki.hypr.land/Configuring/Monitors/
monitor = eDP-1, 3024x1964@120, 0x0, 2

# Input
# Reference: https://wiki.hypr.land/Configuring/Variables/#input
input {
    # Keyboard
    kb_layout = us
    kb_variant = 
    kb_model =
    kb_options =
    kb_rules =
    numlock_by_default = 1

    # Mouse
    sensitivity = 0.5
    accel_profile = adaptive
    follow_mouse = 1
    # force_no_accel = 1

    # Scroll
    scroll_factor = 1
    

    # touchpad
    touchpad {
        natural_scroll = true
        scroll_factor = 0.5
        tap-to-click = false
        clickfinger_behavior = true
        tap-and-drag = false
        # drag_3fg = 1
    }
}

##################
##### Layout #####
##################
# Dwindle
# Reference: https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# Master
# Reference: https://wiki.hypr.land/Configuring/Master-Layout/
master {
    new_status = master
}

scrolling {
    fullscreen_on_one_column = true
    column_width = 0.5
    direction = right
}

################
##### Misc #####
################
# Reference: https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = -1
    disable_hyprland_logo   = false
    vfr = true
}