# Reference: https://wiki.hypr.land/Configuring/Variables/#general
general {
    border_size = 3

    gaps_in  = 5
    gaps_out = 10

    col.active_border   = $active-border-color
    col.inactive_border = $inactive-border-color

    # allow_tearing = true
    layout = scrolling
}