#!/bin/bash

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/events.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
bar=(
    position=top
    height=35
    blur_radius=25
    margin=-11
    corner_radius=10
    y_offset=7
    notch_width=200
    color="$BAR_BG_COLOR"
)

sketchybar --bar "${bar[@]}"   
		
##### Defaults #####
default=(
    background.padding_left=2
    background.padding_right=2
    icon.font="SF Pro:Regular:16.0"
    icon.color=$BAR_COLOR
    label.font="SF Pro:Regular:14.0"
    label.color=$BAR_COLOR
    label.padding_left=5
    label.padding_right=5
    background.color=$ITEM_BG_COLOR
    background.corner_radius=10
    blur_radius=40
)

sketchybar --default "${default[@]}"  

#### Left Side Items ####
source $ITEM_DIR/front_app.sh
source $ITEM_DIR/spaces.sh

#### Right Side Items ####
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/wifi.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/IME.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/brew.sh
source $ITEM_DIR/control.sh

#### Force all scripts to run the first time (never do this in a script) #####
sketchybar  --hotload true
sketchybar  --update
sketchybar  --trigger volume_change