#####################
##### AUTOSTART #####
#####################
exec-once = waybar
exec-once = hypridle
exec-once = systemctl --user start hyprpolkitagent
exec-once = fcitx5 -r -d
exec-once = swww-daemon
exec-once = mako

exec-once = hyprctl keyword 'device[sony-interactive-entertainment-dualsense-wireless-controller-touchpad]:enabled' 'false'

# Clipboard
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = wl-clip-persist --clipboard regular

# Screen Sharing
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Fix: KDE6 StatusNotifierWatcher stopping Waybar
# Reference: https://github.com/Alexays/Waybar/issues/3468
exec-once = printf "[D-BUS Service]\nName=org.kde.kded6\nExec=/bin/false" > $HOME/.local/share/dbus-1/services/org.kde.kded6.service
exec-shutdown = rm $HOME/.local/share/dbus-1/services/org.kde.kded6.service

#################################
##### ENVIRONMENT VARIABLES #####
#################################
# Reference: https://wiki.hypr.land/Configuring/Environment-variables/

# Nvidia
# Reference: https://wiki.hypr.land/Configuring/Environment-variables/#nvidia-specific
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Cursor
# Reference: https://wiki.hypr.land/Hypr-Ecosystem/hyprcursor/
env = HYPRCURSOR_THEME, Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,  24
env = XCURSOR_THEME,    Bibata-Modern-Classic
env = XCURSOR_SIZE,     24

# Qt
# Reference: https://wiki.hypr.land/Configuring/Environment-variables/#qt-variables
env = QT_AUTO_SCREEN_SCALE_FACTOR,          1
env = QT_QPA_PLATFORM,                      wayland;xcb
env = QT_QPA_PLATFORMTHEME,                 qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,  1

### KDE ###
env = XDG_MENU_PREFIX, arch-

### IDK ###
env = EDITOR, vim

### Fcitx ###
env = GTK_IM_MODULE,    fcitx
env = QT_IM_MODULE,     fcitx
env = XMODIFIERS,       "@im=fcitx"

#######################
##### PERMISSIONS #####
#######################
# Reference https://wiki.hypr.land/Configuring/Permissions/
# changes will not auto reload until next restart

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow