# All color values are in RGBA.

[colors] 
background          = eff1f5ff
text                = 5c5f77ff
prompt              = 8839efff
placeholder         = 7c7f93ff
input               = 5c5f77ff
match               = 8839efff
selection           = ccd0daff
selection-text      = 4c4f69ff
selection-match     = 8839efff
counter             = 5c5f77ff
border              = 8839efff