# All color values are in RGBA.

[colors] 
background          = 1e1e2eaa
text                = bac2deff
prompt              = cba6f7ff
placeholder         = 93a1a1ff
input               = bac2deff
match               = cba6f7ff
selection           = 313244ff
selection-text      = cdd6f4ff
selection-match     = cba6f7ff
counter             = bac2deff
border              = cba6f7ff