# tags
keymode=common
bind=super,f5,reload_config
bind=ctrl+alt+shift+super,escape,setkeymode,default

# Keymode
keymode=default
bind=super,r,setkeymode,resize
bind=super+ctrl,f,setkeymode,float

# Resize Mode
keymode=resize

bind=none,Up,resizewin,+0,-50
bind=none,Down,resizewin,+0,+50
bind=none,Left,resizewin,-50,+0
bind=none,Right,resizewin,+50,+0

bind=super,up,focusdir,up
bind=super,down,focusdir,down
bind=super,left,focusdir,left
bind=super,right,focusdir,right

bind=none,h,resizewin,-100,+0
bind=none,j,resizewin,+0,+100
bind=none,k,resizewin,+0,-100
bind=none,l,resizewin,+100,+0

bind=super,h,focusdir,left
bind=super,j,focusdir,down
bind=super,k,focusdir,up
bind=super,l,focusdir,right

bind=super,r,setkeymode,default
bind=none,escape,setkeymode,default

# Fullscreen
keymode=default
bind=super,a,togglemaximizescreen,
bind=super,f,togglefullscreen,
bind=super+shift,f,togglefakefullscreen,

keymode=default
bind=super,prior,viewtoleft,0
bind=super,next,viewtoright,0

# Float Keymode
keymode=float

bind=none,space,togglefloating,

bind=none,c,centerwin

bind=none,up,movewin,+0,-100
bind=none,down,movewin,+0,+100
bind=none,left,movewin,-100,+0
bind=none,right,movewin,+100,+0

bind=none,h,movewin,-100,+0
bind=none,j,movewin,+0,+100
bind=none,k,movewin,+0,-100
bind=none,l,movewin,+100,+0

bind=super+ctrl,f,setkeymode,default
bind=none,escape,setkeymode,default

# Overview Mode
keymode=default
bind=super,tab,overcircle

# spawns
keymode=default
bind=none,XF86AudioRaiseVolume,spawn,~/.local/bin/menus/mediacontrol/dmenu.sh vol_sink_up
bind=none,XF86AudioLowerVolume,spawn,~/.local/bin/menus/mediacontrol/dmenu.sh vol_sink_down
bind=none,XF86AudioMute,spawn,~/.local/bin/menus/mediacontrol/dmenu.sh vol_sink_mute

bind=none,XF86MonBrightnessUp,spawn,~/.local/bin/menus/brightness/dmenu.sh bnctl_up
bind=none,XF86MonBrightnessDown,spawn,~/.local/bin/menus/brightness/dmenu.sh bnctl_down

bind=ctrl+alt,delete,spawn,~/.local/bin/menus/power/dmenu.sh

bind=super,v,spawn,~/.local/bin/menus/palette/dmenu.sh clipboard

bind=super,p,spawn,~/.local/bin/menus/pacman/dmenu.sh