blur=1

windowrule=focused_opacity:0.9,appid:code
windowrule=unfocused_opacity:0.9,appid:code

windowrule=focused_opacity:0.9,appid:foot
windowrule=unfocused_opacity:0.9,appid:foot

windowrule=focused_opacity:0.9,appid:discord
windowrule=unfocused_opacity:0.9,appid:discord