alias brews="brew install"
alias brewu="brew upgrade; brew cu -a"
alias brewc="brew autoremove"
alias brewr="brew uninstall"
alias brewx="brew cleanup"
alias brewf="brew search"
alias brewi="brew info"
