#!/bin/bash

# https://felixkratz.github.io/SketchyBar/config/bar

source "$CONFIG_DIR/variables.sh"

# Bar apperance
bar=(
    color="$BAR_COLOR"
    position=top
    # height=45
    notch_display_height=42
    margin=-10
    # y_offset=-1
    # corner_radius=20
    # blur_radius=50
    notch_width=250
)

default=(
    blur_radius=40

    icon.color="$ITEM_COLOR"
    icon.highlight_color=$ACCENT_COLOR
    icon.padding_left="$I_PAD_L"
    icon.padding_right="$I_PAD_R"
    icon.font="FiraCode Nerd Font:Medium:16.0"

    label.color="$ITEM_COLOR"
    label.padding_left="$L_PAD_L"
    label.padding_right="$L_PAD_R"
    label.font="FiraCode Nerd Font:Medium:16.0"

    background.height=42
    background.color="$ITEM_BG_COLOR"
    background.corner_radius=10
    background.padding_left="$BG_PAD_L"
    background.padding_right="$BG_PAD_R"
)

sketchybar  --bar "${bar[@]}" \
            --default "${default[@]}" \

# Events
sketchybar  --add event is_unlock "com.apple.screenIsUnlocked" \
            --add event input_changed "AppleSelectedInputSourcesChangedNotification" \
            --add event aerospace_workspace_change \
            --add event window_focused \
            --add event title_changed \
            --add event rift_workspace_changed \
            --add event rift_window_title_changed \
            --add event rift_windows_changed

# Components
# source "$CONFIG_DIR/components/spaces.sh"
source "$CONFIG_DIR/components/rift/spaces.sh"
source "$CONFIG_DIR/components/rift/window.sh"

source "$CONFIG_DIR/components/clock.sh"
source "$CONFIG_DIR/components/weather.sh"
source "$CONFIG_DIR/components/network.sh"
source "$CONFIG_DIR/components/battery.sh"
source "$CONFIG_DIR/components/volume.sh"
source "$CONFIG_DIR/components/input.sh"
# source "$CONFIG_DIR/components/brew.sh"

sketchybar --hotload true --update