# Reference: https://wiki.hypr.land/Configuring/Variables/

# Reference: https://wiki.hypr.land/Configuring/Variables/#general
general {
    border_size = 0

    gaps_in  = 0
    gaps_out = 0

    col.active_border   = $active-border-color
    col.inactive_border = $inactive-border-color

    # allow_tearing = true
}

# Reference: https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding            = 0
    rounding_power      = 0

    active_opacity      = 1.0
    inactive_opacity    = 1.0

    blur {
        enabled         = false
    }

    shadow {
        enabled         = false
    }
}

# Reference: https://wiki.hypr.land/Configuring/Variables/#animations
# Reference: https://wiki.hypr.land/Configuring/Animations/#animation-tree
animations {
    # https://www.cssportal.com/css-cubic-bezier-generator/
    # https://easings.net/
    enabled = false
}