# Reference: https://wiki.hypr.land/Configuring/

# Variables
$SCRIPT_DIR = ~/.dotfiles/linux/scripts

# Theme
source = themes/catppuccin_mocha.conf

# Initialize Hyprland
source = hyprland/init.conf

# Load other Config
source = hyprland/appearance.conf
source = hyprland/binds.conf
source = hyprland/rules.conf

#######################
##### Peripherals #####
#######################
# Monitor
# Reference: https://wiki.hypr.land/Configuring/Monitors/
monitor = DP-1, 2560x1440@165, 0x0, 1

# Input
# Reference: https://wiki.hypr.land/Configuring/Variables/#input
input {
    # Keyboard
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = 
    kb_rules =
    numlock_by_default = 1

    # Mouse
    follow_mouse = 1
    force_no_accel = 1
    scroll_factor = 1
}

##################
##### Layout #####
##################
# Dwindle
# Reference: https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# Master
# Reference: https://wiki.hypr.land/Configuring/Master-Layout/
master {
    new_status = master
}

################
##### Misc #####
################
# Reference: https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = -1
    disable_hyprland_logo   = false
}