# Reference: https://wiki.hypr.land/Configuring/

# Variables
$SCRIPT_DIR = ~/.dotfiles/linux/scripts

# Theme
source = themes/catppuccin_mocha.conf

# Set profiles: normal, scrolling, minimal
$PROFILE = hyprland_scrolling

# Load configs
source = $PROFILE/general.conf
source = $PROFILE/layout.conf
source = $PROFILE/init.conf
source = $PROFILE/appearance.conf
source = $PROFILE/binds.conf
source = $PROFILE/rules.conf

#######################
##### Peripherals #####
#######################
# Monitor
# Reference: https://wiki.hypr.land/Configuring/Monitors/
monitor = DP-1, 2560x1440@165, 0x0, 1

# Input
# Reference: https://wiki.hypr.land/Configuring/Variables/#input
input {
    # Keyboard
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = 
    kb_rules =
    numlock_by_default = 1

    # Mouse
    follow_mouse = 1
    force_no_accel = 1
    scroll_factor = 1
}

################
##### Misc #####
################
# Reference: https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = -1
    disable_hyprland_logo   = false
}